src/Entity/NewsletterSubscribe.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsletterSubscribeRepository")
 */
class NewsletterSubscribe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_subscribe;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateSubscribe(): ?\DateTimeInterface
    {
        return $this->date_subscribe;
    }

    public function setDateSubscribe(\DateTimeInterface $date_subscribe): self
    {
        $this->date_subscribe = $date_subscribe;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;
use Symfony\Component\HttpKernel\KernelInterface;

// Entities
use App\Entity\NewsletterSubscribe;

/**
  * Require ROLE_ADMIN for *every* controller method in this class.
  *
  * @IsGranted("ROLE_ADMIN")
  */
class DashboardController extends AbstractController
{
    const NB_SUBS_BY_PAGE = 25;

    /**
     * @Route("/dashboard/reset-cache", name="dashboard_reset_cache")
     */
    public function reset_cache(Request $request, KernelInterface $kernel)
    {
        $application = new Application($kernel);
        $application->setAutoExit(false);

        $input = new ArrayInput([
            'command' => 'cache:clear',
        ]);

        // You can use NullOutput() if you don't need the output
        $output = new NullOutput();
        $run_return = $application->run($input, $output);

        // Data to return / display
        $return_data = array(
            'query_status'      => 0,
            'slug_status'       => 'error',
            'message_status'    => 'Une erreur est survenue lors de la ré-initialisation du cache.'
        );

        if ($run_return == 0) {
            $return_data = array(
                'query_status'    => 1,
                'slug_status'     => 'success',
                'message_status'  => 'Ré-initialisation du cache effectué avec succès.'
            );
        }

        // Set message in flashbag on direct access
        $request->getSession()->getFlashBag()->add($return_data['slug_status'], $return_data['message_status']);

        // Redirect to home
        return $this->redirectToRoute('dashboard');
    }

    /**
     * @Route("/dashboard/{current_page}", name="dashboard", defaults={"current_page"=1})
     */
    public function index($current_page = 1)
    {
        $em     = $this->getDoctrine()->getManager();
        $r_subs = $em->getRepository(NewsletterSubscribe::class);

        $count_subs = $r_subs->countAll();
        $nb_subs    = (int) $count_subs['nb_subs'];

        // Get nb pages of newsletter subscribes
        $nb_pages_raw = ($nb_subs / self::NB_SUBS_BY_PAGE);
        $nb_pages     = floor($nb_pages_raw);

        // If there is decimal numbers,
        //  there is less than 20 subs (=self::NB_SUBS_BY_PAGE) to display
        //  > So we need to add 1 more page
        if (($nb_pages_raw - $nb_pages) > 0)
            $nb_pages++;

        // Check if $current_page is correct, if not redirect with a correct page number
        if ($nb_pages > 0 && $current_page > $nb_pages) {
            $current_page = max(1, $current_page - 1);

            // Redirect with correct $current_page and filters in URI
            return $this->redirectToRoute('dashboard', [ 'current_page' => $current_page ]);
        }

        $subs = $r_subs->findByPage($current_page, self::NB_SUBS_BY_PAGE);

        // Display page with twig & assign values
        return $this->render('dashboard/index.html.twig', [
            'subscribes'    => $subs,
            'nb_subscribes' => $nb_subs,
            'current_page'  => $current_page,
            'nb_pages'      => $nb_pages,
        ]);
    }
}

templates/dashboard/base.html.twig
{# default twig values #}
{% if bg_animated is not defined %}{% set bg_animated = false %}{% endif %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    {# meta.title #}
    <title>
    {%- block meta_title -%}
      {%- if meta.title is defined and meta.title is not empty -%}
        {{ meta.title }} - Dashboard - Kargain World
      {% else %}
        Dashboard - Kargain World
      {%- endif -%}
    {%- endblock -%}
    </title>

    {# meta.desc #}
    {%- block meta_desc -%}
      {% if meta.desc is defined and meta.desc is not empty %}
        <meta name="description" content="{{ meta.desc }}" />
      {% endif %}
    {%- endblock -%}

    {# meta.robots #}
    {% if meta.robots is defined and meta.robots is not empty %}
      <meta name="robots" content="{{ meta.robots }}" />
    {% else %}
      <meta name="robots" content="noindex, nofollow" />
    {% endif %}

    {# Base stylesheets #}
    <link rel="stylesheet" href="{{ asset('build/dashboard.css') }}">
    <link rel="stylesheet" href="{{ asset('build/google-fonts.css') }}">
    {# Custom stylesheets from twig templates #}
    {% block stylesheets %}{% endblock %}
  </head>

  <body class="app-core app-core--dashboard{% if core_class is defined %} {{ core_class }}{% endif %}">
    {# Header #}
    {% block header %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-4">
      <div class="container">
        <a class="navbar-brand" href="{{ path('dashboard') }}">Dashboard</a>
        <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> -->

        <div class="navbar-nav ml-auto">
          <a class="btn btn-sm btn-warning" href="{{ path('dashboard_reset_cache') }}">
            Ré-initialiser le cache
          </a>
        </div>

        <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item{% if app.request.attributes.get('_route') == 'dashboard_newsletter' %} active{% endif %}">
              <a class="nav-link" href="{{ path('dashboard_newsletter') }}">Clients</a>
            </li>
          </ul>
        </div> -->
      </div>
    </nav>
    {% endblock %}

    <div class="app-body{% if body_class is defined %} {{ body_class }}{% endif %}">
      {# Notices/Errors messages from "flashbag" #}
      {% block flashes %}
      <div class="container">
        {% include 'components/flashes.html.twig' %}
      </div>
      {% endblock %}

      {# Body #}
      {% block body %}{% endblock %}
    </div>

    {# Footer #}
    {% block footer %}{% endblock %}

    {# Custom javascripts from twig templates #}
    {% block javascripts_defines %}{% endblock %}

    {# Base javascripts #}
    <script src="{{ asset('build/manifest.js') }}"></script>
    <script src="{{ asset('build/vendors.js') }}"></script>
    <script src="{{ asset('build/dashboard.js') }}"></script>
    {# Custom javascripts from twig templates #}
    {% block javascripts %}{% endblock %}
  </body>
</html>

templates/dashboard/index.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block body %}
<div class="container">
{% if subscribes is defined and subscribes is not empty %}
  <div class="row mb-3">
    <div class="col">
      <h3>Liste des utilisateur&middot;rice&middot;s inscrit&middot;e&middot;s à la newsletter</h3>
    </div>
    <div class="col-12 col-md-auto">
      <a href="{{ path('dashboard_news_subs_download') }}" class="btn btn-primary">
        Télécharger les emails
      </a>
    </div>
  </div>

  <div class="table-responsive table-bordered">
    <table class="table table-striped mb-0">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th>Email</th>
          <th class="text-center">Date</th>
          <th class="text-center"></th>
        </tr>
      </thead>
      <tbody>
        {% for sub in subscribes %}
          <tr>
            <td class="align-middle text-center" style="width: 3rem">{{ sub.id }}</td>
            <td class="align-middle">{{ sub.email }}</td>
            <td class="align-middle text-center" style="width: 7rem">{{ sub.dateSubscribe|date('Y-m-d') }}</td>
            <td class="align-middle text-center" style="width: 6rem">
              <a href="{{ path('dashboard_news_subs_delete', { email: sub.email }) }}"
                class="btn btn-sm btn-danger">
                Suppr.
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="mt-4">
    {# Newsletter subscribes pagination #}
    {% if nb_pages > 1 %}
      <nav class="mb-0" aria-label="Navigation par numéro de page d'utilisateur">
        <ul class="pagination justify-content-center mb-0">
          {# Previous button #}
          {% if current_page > 1 %}
          <li class="page-item">
            <a class="page-link" aria-label="Précédent" href="{{ path('dashboard', { current_page: (current_page - 1) }) }}">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Précédent</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <span class="page-link">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Précédent</span>
            </span>
          </li>
          {% endif %}

          {# Loop to generate numbers pages #}
          {% for num_page in 1..nb_pages %}
            {% if num_page == current_page %}
            <li class="page-item active">
              <span class="page-link">{{ num_page }}</span>
            </li>
            {% else %}
            <li class="page-item">
              <a class="page-link" href="{{ path('dashboard', { current_page: num_page }) }}">
                {{ num_page }}
              </a>
            </li>
            {% endif %}
          {% endfor %}

          {# Next button #}
          {% if current_page < nb_pages %}
          <li class="page-item">
            <a class="page-link" aria-label="Suivant" href="{{ path('dashboard', { current_page: (current_page + 1) }) }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Suivant</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <span class="page-link">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Suivant</span>
            </span>
          </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}

    <div class="mt-1 small text-muted text-center">
      {{ nb_subscribes }} inscription{% if nb_subscribes > 1 %}s{% endif %} à la newsletter.
    </div>
  </div>
{% else %}
  <div class="alert alert-dark">Aucune inscription à la newsletter, pour l'instant.</div>
{% endif %}
</div>
{% endblock %}